# docker compose up -d --build
# docker compose down -v --remove-orphans

version: '3.9'

services:
  cloudflare:
    build:
      context: .
      dockerfile: dockerfile
      no_cache: true
    container_name: cf_cloudflare
    restart: always
    environment:
      REFRESH: $REFRESH #1 (This number is in minutes, where min is 1 and max is 60)
      AUTH_EMAIL: $AUTH_EMAIL #admin@example.com
      AUTH_METHOD: $AUTH_METHOD #token/global
      AUTH_KEY: $AUTH_KEY #1234asdf
      TTL: $TTL #3600 (This number is in seconds, where min is 60 and max is 86400)
      PROXY: $PROXY #true/false
      ZONE_ID_1: $ZONE_ID_1 #1234asdf
      RECORD_NAME_1: $RECORD_NAME_1 #example.com
      ZONE_ID_2: $ZONE_ID_2 #1234asdf
      RECORD_NAME_2: $RECORD_NAME_2 #example.com
      ZONE_ID_3: $ZONE_ID_3 #1234asdf
      RECORD_NAME_3: $RECORD_NAME_3 #example.com
      ZONE_ID_4: $ZONE_ID_4 #1234asdf
      RECORD_NAME_4: $RECORD_NAME_4 #example.com
      ZONE_ID_5: $ZONE_ID_5 #1234asdf
      RECORD_NAME_5: $RECORD_NAME_5 #example.com
      ZONE_ID_6: $ZONE_ID_6 #1234asdf
      RECORD_NAME_6: $RECORD_NAME_6 #example.com
      ZONE_ID_7: $ZONE_ID_7 #1234asdf
      RECORD_NAME_7: $RECORD_NAME_7 #example.com
      ZONE_ID_8: $ZONE_ID_8 #1234asdf
      RECORD_NAME_8: $RECORD_NAME_8 #example.com
      ZONE_ID_9: $ZONE_ID_9 #1234asdf
      RECORD_NAME_9: $RECORD_NAME_9 #example.com
      ZONE_ID_10: $ZONE_ID_10 #1234asdf
      RECORD_NAME_10: $RECORD_NAME_10 #example.com